### PR TITLE
yaml parser support unicode

### PR DESCRIPTION
**Pull request by kunli2**
Update the YAML parser to support multiple bytes (> 2) unicode characters.

Root cause: Snake-yaml parser is based on the characters index and the reader (prefix parsing is based on the reader index) is based on the source index.
If there are any >2 bytes of Unicode characters in the source code, it will make the index mismatch and cause problem.

fixes https://github.com/openrewrite/rewrite/issues/2062

### CODE REVIEW

**Comment by kunli2** [comment]
> what
I think for the big Yaml file, if there are no >2 bytes Unicode characters contained, there is no change so the performance is the same as before.
For the big yaml file which contains >2 bytes Unicode characters, this algorithm is O(1) time complexity and O(N) space complexity, which I think it's fine.

**Comment by kunli2** [comment]
> Can we do a performance benchmark to check what the effect is of this change when parsing big YAML files? Possibly also on the memory overhead.


I think for the big Yaml file, if there are no >2 bytes Unicode characters contained, there is no change so the performance is the same as before.
For the big yaml file which contains >2 bytes Unicode characters, this algorithm is O(1) time complexity and O(N) space complexity, which I think it's fine.

**Comment by knutwannheden** [comment]
I am mostly worried about this index map. While complexity of parsing doesn't increase in terms of Big-O, the parse time could still be considerably increased due to the frequent hashing and resizing. Also, the additional space required is not entirely negligible.

**Comment by kunli2** [comment]
> Can we do a performance benchmark to check what the effect is of this change when parsing big YAML files? Possibly also on the memory overhead.

How to do a performance benchmark? by JMH? I think I need to learn about this

**Comment by knutwannheden** [comment]
Is it correct that while parsing we create one index map entry for each parsed character? So for a 1MB file that would be at least 80MB of memory alone for this map (16 bytes for the map key, 24 bytes for the value, 40 bytes for overhead). Or do we only index some of the characters?

**Comment by knutwannheden** [comment]
Yes, JMH would be the way to go. There are some examples in our repo, but I recommend you read the documentation.

**Comment by kunli2** [comment]
I just realized that the algorithm can be optimized to use a List instead of a map, so we will have no concern about frequent hashing and resizing. updated the code.

**Comment by knutwannheden** [comment]
I see you switched to List. That will be much better. But do we even need the Range? Can't you just get the value for the next element in the list and use that (minus one) as end? Haven't looked at it in detail. And if you then switch to `int[]` it will be a lot more compact and faster.

**Comment by kunli2** [comment]
> I see you switched to List. That will be much better. But do we even need the Range? Can't you just get the value for the next element in the list and use that (minus one) as end? Haven't looked at it in detail. And if you then switch to `int[]` it will be a lot more compact and faster.

I think ranges are required, it needs a start and end, otherwise, the algorithm will not work.
Using int[] instead might be a good idea.

**Comment by kunli2** [comment]
> I see you switched to List. That will be much better. But do we even need the Range? Can't you just get the value for the next element in the list and use that (minus one) as end? Haven't looked at it in detail. And if you then switch to `int[]` it will be a lot more compact and faster.

I see your point, I think after switching to a list instead of a map, we can get rid of range by an int array `int[]` should work.

**Comment by knutwannheden** [comment]
I think you probably don't need the Range object. But I haven't looked at it in detail. If you like I can take a look tomorrow. That would save 20 bytes per character.

**Comment by knutwannheden** [comment]
With only `int[]` you are now down to 4 bytes per character, which is 20 times better than what you first had 🙂

**Comment by kunli2** [comment]
yeah, thanks for the insight! 
polished the algorithm, and I think it has better memory consumption now.

**Review by knutwannheden — APPROVED** [review]
LGTM.

**Comment by knutwannheden** [comment]
An additional overhead of up to 4 bytes per byte should be acceptable. If not, we can still bring it down more.

**Pull request merged**
