### PR TITLE
Revert "Revert "Generify `Validated` to `Validated<T>` (#3014)""

### PR DESCRIPTION
**Pull request by JLLeitschuh**
This reverts commit 75799135767a686ea55495eb00c0da4d96b12006.

This is intended for 8.0

### CODE REVIEW

**Comment by timtebeek** [comment]
A small ping to ask: is this something we want to include now before we announce the 8.0 release?

**Comment by JLLeitschuh** [comment]
That was the intention. @sambsnyd

**Review by sambsnyd — APPROVED** [review]
Since we'll need to redeploy new binaries everywhere anyway I see no reason not to accept this

**Comment by JLLeitschuh** [comment]
Fixing the merge conflicts now

**Comment by JLLeitschuh** [comment]
Merged this

**Pull request merged**
