### PR TITLE
Make `FindMissingTypes` stricter for method invocations

### PR DESCRIPTION
**Pull request by knutwannheden**
Validate argument count with respect to parameter count.

### CODE REVIEW

**Comment by knutwannheden** [comment]
@timtebeek What do you think? We could of course also validate the argument types against the parameter types.

**Comment by timtebeek** [comment]
Yes makes sense to me! Might want to check the same for ParameterNames while we're at it, but otherwise good to add & monitor downstream.

**Comment by knutwannheden** [comment]
Looks like this revealed a bug we have in the Javadoc type attribution.

**Review by timtebeek — APPROVED** [review]
Thanks a lot! Should help harden recipes downstream.

**Pull request merged**
