### PR TITLE
Consistently use OpenRewrite nullness annotations

### PR DESCRIPTION
**Pull request by knutwannheden**
If IDEA hasn't been configured appropriately, sometimes the JetBrains nullness annotations slip in.

### CODE REVIEW

**Review by timtebeek — APPROVED** [review]

**Comment by timtebeek** [comment]
Figured look through the SaaS if there's any others: https://public.moderne.io/results/EuFT6
I'll commit the other ones quickly, but feel free to explore for other such quick fixes as well.

**Comment by timtebeek** [comment]
https://github.com/openrewrite/rewrite-spring/commit/fd58f74e234cb04bd2244949faec03b40d48be3f
https://github.com/openrewrite/rewrite-testing-frameworks/commit/bfa9228ed0456e4ecff1e6abaea0411a234c6e49
And a couple internal ones as well; Good catch!

**Comment by knutwannheden** [comment]
For this I will try to set up an ArchUnit rule.

**Comment by knutwannheden** [comment]
@timtebeek See #2836.

**Pull request merged**
