### PR TITLE
Java parser partial reset

### PR DESCRIPTION
**Pull request by BoykoAlex**
Partial reset of the JavaParser to avoid exception urging to call `reset()`

### CODE REVIEW

**Comment by BoykoAlex** [comment]
Wonder what you think of it... seems to work for us.

**Comment by BoykoAlex** [comment]
Actually, no doesn't work for us... at least not yet :-\

**Comment by BoykoAlex** [comment]
The proposed "light" or "partial" parser reset does the following:
```
       if (!uris.isEmpty()) {
            compilerLog.reset(uris);
        }
        pfm.flush();
        Check.instance(context).newRound();
        Annotate.instance(context).newRound();
        Enter.instance(context).newRound();
        Modules.instance(context).newRound();
```

However, the attached test and IDE integration seem to work if I limit the above to just:
```
        if (!uris.isEmpty()) {
            compilerLog.reset(uris);
        }
        Check.instance(context).newRound();
```

Feels like `pfm.flush()` is a good thing to do. `Check` has method to remove compiled: `removeCompiled(ClassSymbol csym)` which i could have used if we had the `ClassSymbol` from the previously compiled CU (i have this CU but there is no reference to compilers class symbol...

Anyway, "partial" reset in its current form perform and works fine. Mt test java source takes ~180ms to parse after `reset()` and takes ~98ms to parse after "pertial" reset (`reset(Collection<URI>)` that is)

**Comment by BoykoAlex** [comment]
@sambsnyd @jkschneider what do you think of this PR? Is this something that can be merged?

**Comment by sambsnyd** [comment]
Sorry for the slow review, @BoykoAlex. No problems with this jump out at me. I don't know everything about Java compiler internals, but I see no reason to doubt that this is useful.

**Pull request merged**
