### PR TITLE
Unit test odd annotation syntax that is valid but fails to parse

### PR DESCRIPTION
**Pull request by BoykoAlex**
Unit test for #3683

### CODE REVIEW

**Comment by timtebeek** [comment]
Copying the failure here to save folks a click
```
JavaParserTest > annotationAfterVariableTypePackageName() FAILED
    java.lang.AssertionError: 
    Expecting actual:
      ParseError(id=e004c342-f2e6-473b-a69f-b94f377ab22d, markers=Markers(id=19b86423-e451-43b7-a948-0873a8134f03, markers=[ParseExceptionResult(id=314d7f69-9c94-489b-94b5-86945af5737d, parserType=ReloadableJava17Parser, exceptionType=IllegalStateException, message=java.lang.IllegalStateException: example/A.java is not print idempotent.
```
```diff
diff --git a/example/A.java b/example/A.java
index 0ec8d9d..50a1f05 100644
--- a/example/A.java
+++ b/example/A.java
@@ -3,5 +3,5 @@ 
 import example.NonNull;

 public class A {
-  java.lang.@NonNull String a;
+  java.lang.@NonNulljava.lang.Stringing a;
 }
```
```
      org.openrewrite.Parser.requirePrintEqualsInput(Parser.java:52), treeType=null)]), sourcePath=example/A.java, fileAttributes=null, charsetName=UTF-8, charsetBomMarked=false, checksum=null, text=
```
```java
package example;

import example.NonNull;

public class A {
  java.lang.@NonNull String a;
}
```
```
, erroneous=org.openrewrite.java.tree.J$CompilationUnit@65602ca4)
    to be an instance of:
      org.openrewrite.java.tree.J.CompilationUnit
    but was instance of:
      org.openrewrite.tree.ParseError
        at org.openrewrite.java.JavaParserTest.annotationAfterVariableTypePackageName(JavaParserTest.java:120)
```

**Comment by timtebeek** [comment]
It looks like this might go all the way down into how we've defined an annotation signature in Antlr, if I read this correctly. https://github.com/openrewrite/rewrite/blob/8bdf967117c603bffc1533801d6df92a2861cf42/rewrite-java/src/main/antlr/AnnotationSignatureParser.g4#L5-L14

As `AT?` is also valid between the package and class name, we might need to revise the pattern to allow a leading package.
@knutwannheden you're more experienced at this; would you agree with the above? Would that be easy to add?

**Comment by timtebeek** [comment]
@traceyyoshima this still fails with the following, even after https://github.com/openrewrite/rewrite/commit/fbb4e8be7547c25819149bfaa6a7fa3e65987cb1
```
JavaParserTest > annotationAfterVariableTypePackageName() FAILED
    java.lang.AssertionError: 
    Expecting actual:
      ParseError(id=6ba70454-4da8-4f08-9a3d-77757433aa3a, markers=Markers(id=f24a407e-748f-4225-8590-a85cc382ce64, markers=[ParseExceptionResult(id=5a473cd2-531b-476a-82e5-5a616249c508, parserType=ReloadableJava17Parser, exceptionType=IllegalStateException, message=java.lang.IllegalStateException: example/A.java is not print idempotent. 
```
```diff
diff --git a/example/A.java b/example/A.java
index 0ec8d9d..50a1f05 100644
--- a/example/A.java
+++ b/example/A.java
@@ -3,5 +3,5 @@ 
 import example.NonNull;

 public class A {
-  java.lang.@NonNull String a;
+  java.lang.@NonNulljava.lang.Stringing a;
 }
```

I think that might be due the the annotation definition detailed above in https://github.com/openrewrite/rewrite/pull/3684#issuecomment-1829453968

**Comment by traceyyoshima** [comment]
> @traceyyoshima this still fails with the following, even after [fbb4e8b](https://github.com/openrewrite/rewrite/commit/fbb4e8be7547c25819149bfaa6a7fa3e65987cb1)
> 
> ```
> JavaParserTest > annotationAfterVariableTypePackageName() FAILED
>     java.lang.AssertionError: 
>     Expecting actual:
>       ParseError(id=6ba70454-4da8-4f08-9a3d-77757433aa3a, markers=Markers(id=f24a407e-748f-4225-8590-a85cc382ce64, markers=[ParseExceptionResult(id=5a473cd2-531b-476a-82e5-5a616249c508, parserType=ReloadableJava17Parser, exceptionType=IllegalStateException, message=java.lang.IllegalStateException: example/A.java is not print idempotent. 
> ```
> 
> ```diff
> diff --git a/example/A.java b/example/A.java
> index 0ec8d9d..50a1f05 100644
> --- a/example/A.java
> +++ b/example/A.java
> @@ -3,5 +3,5 @@ 
>  import example.NonNull;
> 
>  public class A {
> -  java.lang.@NonNull String a;
> +  java.lang.@NonNulljava.lang.Stringing a;
>  }
> ```
> 
> I think that might be due the the annotation definition detailed above in [#3684 (comment)](https://github.com/openrewrite/rewrite/pull/3684#issuecomment-1829453968)

Ah, commit https://github.com/openrewrite/rewrite/commit/fbb4e8be7547c25819149bfaa6a7fa3e65987cb1 is an update to allow the TypeTree to handle escaped names and is unrelated to annotations on Identifiers.

The comment:
> Note: I think annotations in FQNs may be supported now that we have an annotations field in J.Identifier.
Was in reference to the addition of J.Annotations to J.Identifier [here](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/tree/J.java#L2407).

In an FQN, annotations can be added to J.Identifier, but we need to implement the changes. I can take a look

**Comment by traceyyoshima** [comment]
@timtebeek I think we can close this PR -- I opted to add the test to AnnotationTest and use the test harness so that types are validated, too.

Link to progress on changes: https://github.com/openrewrite/rewrite/pull/3818

**Pull request closed without merging**
