### PR TITLE
Adding `KotlinRewriteTest` to allow named parameters

### PR DESCRIPTION
**Pull request by tkvangorder**

### CODE REVIEW

**Review by sambsnyd — APPROVED** [review]

**Comment by sambsnyd** [comment]
My first impulse was to approve. My second impulse is I'm not sure if I want to add the API surface area and documentation just for named parameters on an API that was made to work nicely without named parameters

**Comment by tkvangorder** [comment]
yep, definitely experimental. @jkschneider Curious if you know any tricks to get extensions working where a kotlin test does not need to extend KotlinRewriteTest? 

The extension methods are actually shadowed by the "real" methods on RewriteTest but the kotlin compiler allows you to use named parameters.

**Review by jkschneider — CHANGES_REQUESTED** [review]
My inclination is to vote no until some justification can be given for why named parameters are needed/desired? Is it just that you were used to named parameters on the old test harness?

I wouldn't want extension methods either. It's just better if there's one way of doing things if that way serves well the use. A slightly different style with no practical benefit just adds confusion.

Named parameters were a play to limit overloads in the original harness while keeping before/after on a particular indentation level. `SourceSpec` carries a lot of that load now.

**Comment by tkvangorder** [comment]
Closing this PR, as it does not really add any significant benefit.

**Pull request closed without merging**
