### PR TITLE
Gradle Enterprise migration recipe

### PR DESCRIPTION
**Pull request by shanman190**

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks for this already; I'm tagging @kunli2 here as he's [already working on applicability tests](https://github.com/openrewrite/rewrite/pull/2727) for a slightly different use case; hopefully he has some insights to share here to help fix the underlying issue that seems to be blocking this pull request.

**Comment by kunli2** [comment]
We filed [ticket](https://github.com/openrewrite/rewrite/issues/2711) for this issue. this is the [PR](https://github.com/openrewrite/rewrite/pull/2727) working in progress intends to fix this issue.

**Comment by timtebeek** [comment]
Ah thanks, I'd missed that one! Good to see you're on it already!

**Comment by timtebeek** [comment]
Would you mind rebasing this one @shanman190 ? Or merge in `main` and then we squash on merge; would like to try again with [the recent fix](https://github.com/openrewrite/rewrite/pull/2727) .

**Comment by shanman190** [comment]
@timtebeek, so this one is still yet a bit more complicated. Was chatting with @sambsnyd about it in Slack and we still need to make a few more tweaks to the tooling model code. The issue here still is the lack of being able to define the initial Gradle version for the test itself. As this stands presently, it fails during model generation as it's running within Gradle 7.x and needs to be running in Gradle <6.0 so that the `com.gradle.build-scan` plugin can apply successfully. On a Gradle >=6.0, it fails stating that the `com.gradle.build-scan` plugin is no longer suitable for the running environment.

**Comment by kunli2** [comment]
Hi @shanman190 , if you merge from `main`, this test will be passed. I have verified it locally.

**Comment by shanman190** [comment]
Awesome! Thanks, @kunli2. I've rebased my PR on top of main and CI is in progress. 😄

**Comment by shanman190** [comment]
@kunli2, I forgot about this until I saw the build failure, but we're still dependent upon improving the testing support when using the Rewrite Gradle Tooling Model before this one can be merged. The recipe itself seems to work correctly though.

**Pull request closed without merging**
