### PR TITLE
Assorted UpdateMavenWrapper fixes

### PR DESCRIPTION
**Pull request by gsmet**
## What's changed?

- Make sure the files are updated in place when updated
- Do not escape colons in the URLs injected in the .properties file. When using `mvn wrapper:wrapper` you don't get colons and they are actually causing issues at least for the `maven-wrapper.jar` as this property is not loaded from Java
- Avoid adding the `maven-wrapper.jar` checksum by default as it's causing issues on Windows due to https://issues.apache.org/jira/browse/MWRAPPER-103 -> this is probably something we need to discussed

## What's your motivation?

- https://github.com/openrewrite/rewrite/issues/3982
- Discussions in https://github.com/quarkusio/quarkus/issues/38569

## Anything in particular you'd like reviewers to focus on?

I didn't have the time to add tests for the first commit yet. I'll have a look at it in the next days as time permits if nobody beats me to it.

## Anyone you would like to review specifically?

@timtebeek @shanman190 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

^ Is there a way to apply the formatter with a command line? I'm all for formatting rules but not using Intellij atm. I suppose I could try to use it if there are no other option.

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks a lot for the in depth look for these various fixes. Added a test for the subdir handling to update the same files just now. I'm not sure what the backstory was on those escaped colons for properties, but that seems to have been added in
- https://github.com/openrewrite/rewrite/pull/3392

@shanman190 do you recall what was behind that, and if we need it for any particular case still? Otherwise good to merge if you ask me.

**Comment by shanman190** [comment]
So that's actually because I copied from the `UpdateGradleWrapper` recipe that I wrote. I kinda made the assumption that Maven would have scavenged at least a fair bit of the code from Gradle, but it appears in this particular case they didn't.

On the Gradle side, they read and write the properties using `java.util.Properties`. When a `store` operation is executed, it escapes the `:` character, so during a `gradle wrapper` or `gradlew wrapper` cycle, the end resulting properties file will be escaped. Now the one aspect that Gradle then goes an manipulates is by writing the output to memory, then removing the header, and finally writing that as the result to disk. Maven on the other hand appears to just write the properties using a `BufferedWriter` instead rather than the `java.util.Properties` interface. 

Now with that said, the `wrapperUrl` is parsed out of the properties by the shell scripts, then used to directly download the wrapper.jar if it's missing. Since this is used in a shell script, being escaped would likely result in a few issues. Downloading the wrapper.jar file in the script is not something that is supported on the Gradle side, so that's why this issue never presents over there.

**Comment by shanman190** [comment]
I went ahead and reworded/renamed a few things with respect to the new option.

I also wanted to point out that this particular `Get-FileHash` isn't a Maven Wrapper or Windows issue in itself. `Get-FileHash` is a function that ships with the PowerShell for every Windows OS version. However, when PowerShell Core installs badly and then is used, such as is the case within GitHub runners at present it appears, then the core PSModulePath can effectively be hidden from view resulting in those core cmdlets not being available for use. So the issue isn't technically a Windows (general) incompatibility, but nonetheless it occurred in the ecosystem where folks work from. As such, I removed that note, but did add the issue link in the description markdown as a possible example implication of what enabling that feature can result in occurring.

**Review by shanman190 — APPROVED** [review]
Thanks for the work here to fix this issue, @gsmet!

**Comment by gsmet** [comment]
Thanks to both of you!

**Pull request merged**
