### PR TITLE
Decreased yaml coalescing occurrences (#1841)

### PR DESCRIPTION
**Pull request by nmck257**
Removed coalescing from Yaml ChangePropertyKey, and deprecated coalescing in DeleteProperty and YamlVisitor (#1841)

Let me know if we want to adjust any details of the deprecation(s)

### CODE REVIEW

**Comment by pway99** [comment]
Thanks @nmck257, 
This is a good change I would suggest also removing the `org.openrewrite.yaml.ChangePropertyKey nonScalarMappingEntryExists(..)` method which will no longer be unused.

**Comment by nmck257** [comment]
> Thanks @nmck257, This is a good change I would suggest also removing the `org.openrewrite.yaml.ChangePropertyKey nonScalarMappingEntryExists(..)` method which will no longer be used.

done!

**Comment by nmck257** [comment]
heads up -- I also just slipped in another tiny fix from #1841 (extraneous newline at beginning of file)

**Comment by pway99** [comment]
Hi @nmck257, 
Thanks for identifying https://github.com/openrewrite/rewrite/issues/1873.  
I reverted these changes from the 7.24.0 release, which will give us some time to fix everything up for 7.25.0.

**Pull request merged**
