### PR TITLE
Test coverage for change package of static import enum (issue in rewrite 7.33.0 but not 7.34.0-SNAPSHOT)

### PR DESCRIPTION
**Pull request by ge0ffrey**
Couldn't build locally (see slack), so not sure this actually reproduces it yet, until CI kicks in.

Related to https://github.com/openrewrite/rewrite/issues/2439

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Just seen it happen with single static import too, so this (hopefully) reproducer is unneeded complex.

**Comment by ge0ffrey** [comment]
```
2022-11-18T16:09:16.0543221Z Java8VisitorCompatibilityTest > ChangePackageTck > staticImport2(JavaParser) FAILED
2022-11-18T16:09:16.0543454Z     java.lang.IllegalStateException: AST contains missing or invalid type information
2022-11-18T16:09:16.0543940Z     Identifier->Binary->Binary->MethodInvocation->ControlParentheses->If->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
2022-11-18T16:09:16.0544107Z     /*~~(Identifier type is missing or malformed)~~>*/B1
2022-11-18T16:09:16.0544116Z 
2022-11-18T16:09:16.0544544Z     Identifier->Binary->MethodInvocation->ControlParentheses->If->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
2022-11-18T16:09:16.0544708Z     /*~~(Identifier type is missing or malformed)~~>*/B2
2022-11-18T16:09:16.0544955Z         at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:83)
2022-11-18T16:09:16.0545220Z         at org.openrewrite.java.TypeValidator$Companion.assertTypesValid(TypeValidator.kt:61)
2022-11-18T16:09:16.0545518Z         at org.openrewrite.java.JavaRecipeTest$assertChanged$typeValidatingAfterConditions$1.invoke(JavaRecipeTest.kt:62)
2022-11-18T16:09:16.0545812Z         at org.openrewrite.java.JavaRecipeTest$assertChanged$typeValidatingAfterConditions$1.invoke(JavaRecipeTest.kt:61)
2022-11-18T16:09:16.0546061Z         at org.openrewrite.RecipeTest$DefaultImpls.assertChangedBase(RecipeTest.kt:132)
2022-11-18T16:09:16.0546299Z         at org.openrewrite.RecipeTest$DefaultImpls.assertChangedBase(RecipeTest.kt:60)
2022-11-18T16:09:16.0546546Z         at org.openrewrite.java.JavaRecipeTest$DefaultImpls.assertChanged(JavaRecipeTest.kt:66)
2022-11-18T16:09:16.0546824Z         at org.openrewrite.java.ChangePackageTest$DefaultImpls.assertChanged(ChangePackageTest.kt:27)
2022-11-18T16:09:16.0547159Z         at org.openrewrite.java.JavaVisitorCompatibilityKit$ChangePackageTck.assertChanged(JavaVisitorCompatibilityKit.kt:112)
2022-11-18T16:09:16.0547422Z         at org.openrewrite.java.JavaRecipeTest$DefaultImpls.assertChanged$default(JavaRecipeTest.kt:49)
2022-11-18T16:09:16.0547700Z         at org.openrewrite.java.ChangePackageTest$DefaultImpls.staticImport2(ChangePackageTest.kt:884)
2022-11-18T16:09:16.0548088Z         at org.openrewrite.java.JavaVisitorCompatibilityKit$ChangePackageTck.staticImport2(JavaVisitorCompatibilityKit.kt:112)
```

**Comment by traceyyoshima** [comment]
Hi @ge0ffrey, I think the issue may be related to the package name of `EnumB`, which is currently `enuma` and should be `enumb`.

**Comment by ge0ffrey** [comment]
@traceyyoshima You're right, that compilation error fixes it.
Although it seems that the issue doesn't reproduce in this isolated code on 7.34.0-SNAPSHOT. If CI turns green, it will prove that.

I can reproduce the issue multiple times with rewrite-maven-plugin 4.37.0 that uses rewrite 7.33.0.

**Comment by ge0ffrey** [comment]
Ok, I just ran with rewrite-maven-plugin 4.38.0-SNAPSHOT and I cannot reproduce the issue. So this PR just increases test coverage, the issue is already fixed.

Feel free to close without merging or with merging, as you see fit.

**Comment by traceyyoshima** [comment]
Hi @ge0ffrey, regardless, thank you for reporting the issue!

Closing the PR as it is fixed on the main branch.

**Comment by ge0ffrey** [comment]
@traceyyoshima I just saw the issue reoccur in the latest SNAPSHOT of the maven plugin.

The main branch currently has no test coverage for static enum imports AFAIK (even if this PR isn't clean enough, it might act as a starting point?)

**Comment by traceyyoshima** [comment]
> @traceyyoshima I just saw the issue reoccur in the latest 4.38.0-SNAPSHOT of the maven plugin.
> 
> The main branch currently has no test coverage for static enum imports AFAIK (even if this PR isn't clean enough, it might act as a starting point?)

Hi @ge0ffrey thank you for bringing this up again — I’ll take a look first thing on Monday!

**Comment by ge0ffrey** [comment]
I rebased this PR on main and ran the tests and they succeeded. I need to figure out what's different when I run the snapshot and the static imports don't migrate.

**Comment by traceyyoshima** [comment]
> I rebased this PR on main, but it seems as the new test in this PR succeeded.

Okay, sounds good - I'm happy to help if it stops working.

**Comment by ge0ffrey** [comment]
The real-world issue is still there, with rewrite version 7.34.0-SNAPSHOT build locally today.
I need to find a way to isolate and reproduce it.

**Comment by ge0ffrey** [comment]
Ok, I found the extra condition to reproduce: the statically important enums must be in the same package.
I'll create a new PR and a new issue for clarity.

**Comment by ge0ffrey** [comment]
New reproducer: https://github.com/openrewrite/rewrite/pull/2470

**Pull request closed without merging**
