### PR TITLE
Do not downgrade SourceCompatibility by default

### PR DESCRIPTION
**Pull request by timtebeek**
Fixes https://github.com/openrewrite/rewrite/issues/3938

### CODE REVIEW

**Comment by shanman190** [comment]
@timtebeek, something interesting here is that the intermediate recipe already has a strict check for strict upgrade. 

https://github.com/openrewrite/rewrite-migrate-java/blob/main/src%2Fmain%2Fjava%2Forg%2Fopenrewrite%2Fjava%2Fmigrate%2FUpgradeJavaVersion.java#L69

**Comment by timtebeek** [comment]
Hmm that is odd indeed; that conditional looks for the JavaVersion marker on `build.gradle files`, but when I look at the Gradle plugin to see [we create the JavaVersion marker](https://github.com/openrewrite/rewrite-gradle-plugin/blob/dd0617f3ecfe4d332f6a06665229c4ddc2345b29/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L664-L667), but at first glance I only see that added to Java, Kotling and `.groovy` files, not the build.gradle files we evaluate here. Am I missing something? Or should we add those markers to Gradle files too still?

I think this might have only shown up now as folks start to run recipes that chain in a Java 17 migration while being on Java 21; it's been rare that we had cases where folks are on newer Java versions from what we prescribe.

**Comment by shanman190** [comment]
Ok, now I see what happened. The `UpgradeJavaVersion` recipe pre-8.0 actually added the `JavaVersion` marker to every LST element as if performed that targeted upgrade. This was then used to block the downgrading automatically. When it was converted to 8.x it now is only conditionally adding the markers. So to your point, if things aren't aligned with the prescriptive guidance, then it now acts funny. 

So longer story short, I think your change does in fact fix the issue fully, but we do have some dead code in the `UpgradeJavaVersion` recipe to now misleading behavior.

**Comment by timtebeek** [comment]
Picked that up in https://github.com/openrewrite/rewrite-migrate-java/pull/400 to prevent any confusion, thansk!

**Pull request merged**
