### PR TITLE
Fix method name collisions with UseStaticImport

### PR DESCRIPTION
**Pull request by protocol7**
Ensure that an import static is not created if a method with the same name already exists, either locally (this fixes this to take into account package name) or already imported statically.

- Fixes https://github.com/openrewrite/rewrite/issues/4304

### CODE REVIEW

**Comment by protocol7** [comment]
This adds failing tests for now.

**Comment by timtebeek** [comment]
Thanks for kicking this off @protocol7 ; was triggered to have a look, and hope you don't mind me solving this one.

I only just now saw your https://github.com/openrewrite/rewrite/issues/4304#issuecomment-2211719725 

> > I think extending the preconditions with a separate visitor that looks at static imports used might be best

> I'm not sure how to define this. I gather I could use UsesMethod, but not sure how to write the method pattern in a way that includes any other method named, say, "foo", except for the method we are trying to rewrite.

You'll see I went for defining a new visitor that specifically looks for other static imports of the same name, and if found return a search result indicating that the `Precondition.not` should not visit the source file further. Hope that helps you on a future recipe!

https://github.com/openrewrite/rewrite/blob/f4da66ae5a48bed24ec3d889e42b5e2761f8975e/rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java#L64-L72

**Review by timtebeek — APPROVED** [review]
Thanks a lot! The `DeclaresMethod` fix and additional tests were already a great help. Beyond that it was a matter of adding a new precondition visitor that merely looks at existing imports. The way recipes run in sequence also means that your test using two `new UseStaticImport` could replace the first case, but not the second, as the second time around we see the modified model and imports as output from the first recipe. Hope you'll agree and this helps you along.

**Comment by protocol7** [comment]
Perfect, thanks for finishing this one up!

**Pull request merged**
