### PR TITLE
GradleParserTest: with import statement

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
The CI build failed with this error:

```
GradleParserTest > buildGradleAndSettingsGradle() STANDARD_OUT
[8443](https://github.com/openrewrite/rewrite/actions/runs/3796966174/jobs/6457519346#step:7:8445)
    doesntmatter: 90: Unexpected input: 'import' @ line 90, column 24.
[8444](https://github.com/openrewrite/rewrite/actions/runs/3796966174/jobs/6457519346#step:7:8446)

[8445](https://github.com/openrewrite/rewrite/actions/runs/3796966174/jobs/6457519346#step:7:8447)
           void __script__() {import java.nio.file.Files
```

**Comment by sullis** [comment]
cc: @tkvangorder

**Comment by sambsnyd** [comment]
Hi @sullis , we are aware of this issue with parsing gradle scripts which include imports, class definitions, or function definitions. It should be fixed soon when we merge #2613

**Comment by sambsnyd** [comment]
@sullis good news that PR got merged so this should work now 👍

**Pull request closed without merging**
