### PR TITLE
Add recipe to replace text blocks with strings

### PR DESCRIPTION
**Pull request by AresEkb**
Maybe such a recipe will be useful, if it doesn't already exist.

### CODE REVIEW

**Comment by timtebeek** [comment]
Sympathize with you there having to downgrade and appreciate the recipes!

Just to be sure we've covered all cases, would you mind adding a test with a comment just before the text block? Want to make sure we're not accidentally removing those comments with the current implementation, or any changes after this is merged.

**Comment by timtebeek** [comment]
In either case these tests are going to come in handy (in reverse) when we implement #2742, and hopefully for you in the future!

**Comment by AresEkb** [comment]
I agree that comments should not be removed. Added tests and fixed the recipe.

**Comment by sambsnyd** [comment]
Thanks for contributing all of these back, @AresEkb !

**Pull request merged**
