### PR TITLE
Add a failing test in ReplaceStringBuilderWithStringTest

### PR DESCRIPTION
**Pull request by pramud**

### CODE REVIEW

**Comment by rpau** [comment]
Thanks for reporting this failing test!

**Comment by timtebeek** [comment]
Thanks! We can indeed try to replicate the issue here, but any fix should go into the new rewrite-static-analysis, such that it's not lost with the upcoming 8.0

**Comment by kunli2** [comment]
hi @pramud , thanks for looking into this, however, this case doesn't work because it doesn't compile.

I changed the code a bit to pass compile and it works.
```java

    @Test
    void withMethods() {
        rewriteRun(
          java(
            """
              class A {
                  void method() {
                      String key0 = new StringBuilder().append("test".toUpperCase()).append(3).append(count()).toString();
                  }
                  int count() {
                      return 10;
                  }
              }
              """
            ,
            """
              class A {
                  void method() {
                      String key0 = "test".toUpperCase() + 3 + count();
                  }
                  int count() {
                      return 10;
                  }
              }
              """
          )
        );
    }
```

**Comment by kunli2** [comment]
closing out this, please let me know if you still have any concerns or new findings. Thanks in advance.

**Pull request closed without merging**
