### PR TITLE
ChangePackage fails to migrate annotation argument enum in package-info

### PR DESCRIPTION
**Pull request by pativa**
## What's changed?
I found [this issue](https://github.com/openrewrite/rewrite/issues/3200) describing problems with migrating annotations in `package-info.java`. We seem to still have this problem.

In this MR, I have added a (failing) test showing our issue.

Our actual issue is regarding applying jakarta migration for this class:

```
@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example;
```

We have made it work using `org.openrewrite.java.ChangeType` for our migration, but would prefer if `org.openrewrite.java.ChangePackage` worked for this.

## Anything in particular you'd like reviewers to focus on?

Please note that this does not fix the issue, only adds a test case to it :-)

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks a lot! Runnable tests are my favorite way to show a bug; did you already try to step through with a debugger to see if you could pinpoint the source of the issue?

**Comment by pativa** [comment]
No, I haven't found the source of the issue. It seems to find that the types are in use, but the changes are not applied.

I can maybe check it out later if you haven't already found it!

**Comment by pativa** [comment]
The fix was really simple when I finally found what was going on 🙂 

The `visitPackage` method was not calling `super.visitPackage()`, so annotations on the package statement weren't being updated.

**Review by timtebeek — APPROVED** [review]
Yes makes sense when you see the issue; thanks for digging in and providing the fix!

**Comment by pativa** [comment]
I'm not really sure of why, but some tests were failing if `super.visitPackage()` is called.

Instead, I updated the proposed fix to only update the annotations in the same way as is done inside the super method. This seems to work with all the existing tests at least.

**Pull request merged**
