### PR TITLE
Use type cache when it's available in JavaExecutionContextView.

### PR DESCRIPTION
**Pull request by traceyyoshima**

### CODE REVIEW

**Review by tkvangorder — APPROVED** [review]
LGTM, good catch.

**Comment by tkvangorder** [comment]
To clarify this change:

Previously, if the type cache was not explicitly set on a context, the java context view would fall back to the default. A new instance of the JavaExecutionContextView is used each time (resulting in a different default, empty cache) during each parse. This resulted in memory exhaustion because there was no type sharing across JavaParsingVisitors.

**Comment by jkschneider** [comment]
Reverting, as I think this has no effect. On the subsequent call to getMessage it just returns the message with the key rather than the default, which is the same instance.

**Comment by jkschneider** [comment]
@tkvangorder Please revert.

**Comment by jkschneider** [comment]
There is one execution context instance per parsing operation (over a whole source set or project). Thus, there should be a unique type cache per parsing operation. This is WAD.

**Comment by murdos** [comment]
@jkschneider : on my side this fixed a huge regression (very long parsing with a lot of heap space)

**Pull request merged**
