### PR TITLE
Align plugin configuration with updates needed for rewrite-recipe-bom

### PR DESCRIPTION
**Pull request by shanman190**

### CODE REVIEW

**Comment by shanman190** [comment]
So I'm thinking that this is at least a starting place for this. Given there is the desire to additionally have recipe jars included as well, this _may_ have to entirely be a net new project otherwise we will have a circular dependency that can't be broken.

Ex: rewrite-core -> rewrite-spring -> rewrite-all

**Comment by jkschneider** [comment]
`rewrite-all` should be acyclic in the end.

image

However, this can't be an included project of the multi-module project rewrite project. It could use the same build almost, but would probably have a different version (so shouldn't be in the same repo driven by the same set of tags).

I think we could accomplish the inclusion of downstream projects by listing them here and including the rest of the rewrite language modules via a composite, but this still wouldn't solve the versioning issue. We could forgo nebula release and version `rewrite-all` with `2021.4.13` or something? Then it could be in this project, as long as it is published with a separate github action workflow that we trigger after all downstreams are built.

**Comment by shanman190** [comment]
So since this module would have to be disconnected both from this repository's Gradle project, but also need to consume the recipe projects as diagramed, how does a new repository sound to hold this particular use case?

I bounced some ideas in terms of that particular path off of @sambsnyd and we were thinking that maybe what you have as `rewrite-all` becomes just simply a BOM for the purposes of providing version alignment. End users are still responsible for bringing in what they _need_ as part of the selection, but would ease the versioning issue as described in the original issue.

On this path, we were thinking that maybe we'd leave openrewrite/rewrite the way that it is today, then create a repository that was only responsible for publishing the java platform for something like `org.openrewrite.recipes:rewrite-recipes-bom` which would depend upon the `org.openrewrite:rewrite-bom:latest.release` (resolved to <rewriteVersion>) and each of the specific recipe jars -- `org.openrewrite.recipes:rewrite-spring:latest.release` (also resolved to <rewriteSpringVersion>). Then with each release of either core OR recipes OR adding a new recipes, the `rewrite-recipes-bom` project would be launched to version align everything based upon current processes.

Thoughts?

**Comment by tkvangorder** [comment]
@shanman190 This all looks reasonable to me. Chatting with Sam, he just created a new repo https://github.com/openrewrite/rewrite-recipe-bom to host the new module.

**Comment by shanman190** [comment]
Added bom over at https://github.com/openrewrite/rewrite-recipe-bom/pull/1.

Going to rework this PR to align with the `rewrite-recipes-bom` PR.

**Pull request merged**
