### PR TITLE
Fixes for type attribution and `TypeUtils#isAssignableTo()`

### LINKED ISSUE #4423: `JavaTemplateSemanticallyEqual` fails to match AssertJ's `assertThat("foo").isEqualTo("")`
## What version of OpenRewrite are you using?
https://github.com/openrewrite/rewrite/releases/tag/v8.33.4

## Problem statement
This recipe replicates what's generated from our Refaster template generator:
- https://github.com/openrewrite/rewrite-templating/pull/91

Based on a Refaster rule defined at Picnic
- https://error-prone.picnic.tech/refasterrules/AssertJStringRules/#abstractstringassertstringisempty

We might want to quickly double check the String passed in to `JavaTemplate.builder`.

## What is the smallest, simplest way to reproduce the problem?
```java
import org.junit.jupiter.api.Test;
import org.openrewrite.ExecutionContext;
import org.openrewrite.Issue;
import org.openrewrite.java.tree.J;
import org.openrewrite.marker.SearchResult;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.java.Assertions.java;
import static org.openrewrite.test.RewriteTest.toRecipe;

class JavaTemplateMatcherTest implements RewriteTest {

    @Test
    @Issue("https://github.com/openrewrite/rewrite-templating/pull/91")
    void shouldMatchAbstracTStringAssertIsEqualToEmptyString() {
        rewriteRun(
          spec -> spec
            .parser(JavaParser.fromJavaVersion().classpath("assertj-core"))
            .recipe(toRecipe(() -> new JavaIsoVisitor<>() {
                // Mimics what we saw in rewrite-templating
                final JavaTemplate before = JavaTemplate
                  .builder("#{stringAssert:any(org.assertj.core.api.AbstractStringAssert<?>)}.isEqualTo(\"\");")
                  .javaParser(JavaParser.fromJavaVersion().classpath(JavaParser.runtimeClasspath()))
                  .build();

                @Override
                public J.MethodInvocation visitMethodInvocation(J.MethodInvocation method, ExecutionContext ctx) {
                    J.MethodInvocation mi = super.visitMethodInvocation(method, ctx);
                    return before.matches(getCursor()) ? SearchResult.found(mi) : mi;
                }
            })),
          //language=java
          java(
            """
              import static org.assertj.core.api.Assertions.assertThat;
              class Foo {
                  void test() {
                      assertThat("foo").isEqualTo("");
                  }
              }
              """,
            """
              import static org.assertj.core.api.Assertions.assertThat;
              class Foo {
                  void test() {
                      /*~~>*/assertThat("foo").isEqualTo("");
                  }
              }
              """
          )
        );

    }
}
```

## What is the full stack trace of any errors you encountered?
```
java.lang.AssertionError: Recipe was expected to make a change but made no changes.
```

### PR DESCRIPTION
**Pull request by knutwannheden**
Try to fix #4423 by correcting the type attribution for some generics and the corresponding type assignability check.

- Fixes: #4423

### CODE REVIEW

**Comment by knutwannheden** [comment]
@timtebeek I believe this will cause some test failures, but I do believe that there is currently something missing in the type attribution, which causes the test from #4423 to fail.

This is WIP and I am not sure when I will be able to pick this up. Maybe you find the time 😉

**Comment by timtebeek** [comment]
Indeed seeing three new falures; quick link to one of them here for reference.
[:rewrite-java-test:test](https://ge.openrewrite.org/s/tymn7rglh7u2u/tests/task/:rewrite-java-test:test)  [org.openrewrite.java.JavaTemplateSubstitutionsTest](https://ge.openrewrite.org/s/tymn7rglh7u2u/tests/task/:rewrite-java-test:test/details/org.openrewrite.java.JavaTemplateSubstitutionsTest)

```diff
diff --git a/Test.java b/Test.java	
index b025685..8109464 100644	
--- a/Test.java	
+++ b/Test.java	
@@ -1,6 +1,6 @@ 	
 import java.util.Map;	
 class Test {	
  void test(Map<String, ?> map) {	
-     System.out.println(map.get("test"));	
+     System.out.println(__P__.<error> << captured wildcard>>/*__p0__*/p();	
  }	
 }	
```

**Comment by knutwannheden** [comment]
@timtebeek I pushed another commit. Let's see if this helps. Got any idea if any recipes have bugs which can be explained by this?

**Comment by timtebeek** [comment]
> @timtebeek I pushed another commit. Let's see if this helps. Got any idea if any recipes have bugs which can be explained by this?

Thanks a lot! I don't recall us using `JavaTemplate.matches` much outside of Refaster recipes, and within Refaster recipes I think we've mostly then had cases that failed to match. That's still a bug, but not as impactful as a false positive match would be. I do expect to see improvement to the cases matched through the ErrorProne Support set of recipes, and being able to leverage those more for our migrations as we've started to do in rewrite-testing-frameworks.

Would you need me to apply the same fixes to the other versions of Java parsers?

**Comment by knutwannheden** [comment]
Yes, I believe we should apply the same fix to the other Java parsers.

**Review by anandfresh — COMMENTED** [review]
LGTM

**Comment by knutwannheden** [comment]
Also note that the bug could affect any recipes which direcly or indirectly use TypeUtils.isAssignableTo(). So this isn't restricted to Refaster of JavaTemplate.matches(), but it is still an uncommon corner case.

**Review by timtebeek — APPROVED** [review]
Thanks a lot for finding some time to squeeze this in! Should make those matchers a lot more effective, and unlocks more reuse through Refaster.

**Comment by timtebeek** [comment]
Seeing one downstream test failure (so far) in rewrite-static-analysis
https://github.com/openrewrite/rewrite-static-analysis/blob/195fbf806ce214305d59d92e81bf2bef7401cf9c/src/test/java/org/openrewrite/staticanalysis/ExplicitLambdaArgumentTypesTest.java#L618-L648

```
ExplicitLambdaArgumentTypesTest > extendsConstraint() FAILED
    org.opentest4j.AssertionFailedError: [Unexpected result in "com/test/A.java":
    diff --git a/com/test/A.java b/com/test/A.java
    index b70fd0e..46a199b 100644
    --- a/com/test/A.java
    +++ b/com/test/A.java
    @@ -4,6 +4,6 @@ 
 
     class A {
         void foo(List<? extends A> a) {
    -        a.forEach((A it) -> { });
    +        a.forEach((<captured wildcard> it) -> { });
         }
     }
    \ No newline at end of file
    ] 
    expected: 
      "package com.test;
  
      import java.util.List;
  
      class A {
          void foo(List<? extends A> a) {
              a.forEach((A it) -> { });
          }
      }"
     but was: 
      "package com.test;
  
      import java.util.List;
  
      class A {
          void foo(List<? extends A> a) {
              a.forEach((<captured wildcard> it) -> { });
          }
      }"
        at app//org.openrewrite.test.RewriteTest.assertContentEquals(RewriteTest.java:616)
        at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:507)
        at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:132)
        at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:127)
        at app//org.openrewrite.staticanalysis.ExplicitLambdaArgumentTypesTest.extendsConstraint(ExplicitLambdaArgumentTypesTest.java:621)
```

**Comment by knutwannheden** [comment]
Looks like it requires slightly more work.

**Pull request merged**
