### PR TITLE
Make markers responsible for printing themselves. Fixes #412

### LINKED ISSUE #412: SourceFile implementations should include default SearchResultPrinters
Currently we have no straightforward way of printing SearchResult markers when running via our build plugins.
This means that search recipes run but produce no visible output.
As a first step to fixing this, we need to have a default SearchResultPrinter for each type of SourceFile. These default search result printers must print markers inside of a context-appropriate comment so that reifying the markers to code changes doesn't result in broken code. e.g.: `/* ~~> */` for Java and `<!-- ~~> -->` for XML

### PR DESCRIPTION
**Pull request by sambsnyd**

### CODE REVIEW

**Comment by sambsnyd** [comment]
I'm not finished with this yet but what do you guys think of the basic approach @jkschneider @tkvangorder  ?

**Review by tkvangorder — COMMENTED** [review]
Just curious about the motivation for dropping the type parameter?

**Comment by tkvangorder** [comment]
The subclasses of the printer make sense, I like it.

**Comment by sambsnyd** [comment]
Going to go a different direction than this. New PR soon

**Pull request closed without merging**
