### PR TITLE
fix invalid jarPattern in JavaParser

### PR DESCRIPTION
**Pull request by ckcd**
## What's changed?

Fix invalid pattern in https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java#L123

The `file.getName()` and pattern `Pattern.compile("[/\\\\]" + artifactName + "-?.*\\.jar$")` is mismatch so that the pattern.matcher will always be `false`. The `file.getName()` returns a simple filename without any `/` but the pattern needs a `/`.

See more details in https://github.com/openrewrite/rewrite/issues/4123

## What's your motivation?

Fix https://github.com/openrewrite/rewrite/issues/4123

## Anything in particular you'd like reviewers to focus on?

No

## Anyone you would like to review specifically?

No

## Have you considered any alternatives or workarounds?

No

## Any additional context

No

### Checklist
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by ckcd** [comment]
@traceyyoshima @knutwannheden could you please take a look at this PR? thanks.

**Comment by timtebeek** [comment]
Thanks a lot @ckcd for the detailed write up in 
- #4124 
And the subsequent fix here. Surprised this hadn't been flagged before, but your explanation makes sense.

**Comment by ckcd** [comment]
@timtebeek Thanks for your reply!

**Pull request merged**
