### PR TITLE
Refactor references updating

### PR DESCRIPTION
**Pull request by nielsdebruin**
## What's changed?

This PR introduces an initial attempt at refactoring the updating references for properties and YAML files. The effect is both improved performance and decoupling.

## What's your motivation?
A `Reference` has a "value" of type `String`. However, implementation-wise, the underlying `Reference` only has a `Cursor`, from which we retrieve the `Tree`. The specific implementation of the `Reference` interface will map this to a `String` depending on the type which becomes the value. 

For example, in the `Properties` reference, this would look like:

```java
@Override
public @NonNull String getValue() {
    if (getTree() instanceof Properties.Entry) {
        return ((Properties.Entry) getTree()).getValue().getText();
    }
    throw new IllegalArgumentException("getTree() must be a Properties.Entry: " + getTree().getClass());
}
```

Currently, the specific implementations for different types of references are handled in the TypeMatcher and PackageMatcher classes. This leads to code duplication and increased coupling. Moreover, both classes generate a new visitor for each reference update, which is inefficient. This refactor moves the specific implementation to the `Reference` interface by introducing a `withValueFromString(String newValue)` method in Reference. This method can be used when implementing the newly introduced `ReferenceUpdateFunction`.

## Anyone you would like to review specifically?

@timtebeek @Laurens-W

### Checklist
- [] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by knutwannheden** [comment]
With `supportsUpdate()` etc. we are now adding new methods for which `supportsRename()` was intended. I was actually thinking of something simpler along the lines of the following. The thing I am unsure about is what the signature of that `Reference#rename()` should look like. In my patch it is now like this:

```java
    default Tree rename(Renamer renamer, Cursor cursor, ExecutionContext ctx) {
        return cursor.getValue();
    }
```

Passing in the input `Tree` (or `Cursor` as here) is only required, if other changes have been made in the meantime. If the caller makes sure to call this method from `postVisit()` rather than `preVisit()` that would not be an issue. By passing in the `Tree` we don't have to care. Unsure about that part. Also, the `Renamer` API is possibly to simplistic.

Thoughts?

```patch
Index: rewrite-java/src/main/java/org/openrewrite/java/PackageMatcher.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/rewrite-java/src/main/java/org/openrewrite/java/PackageMatcher.java b/rewrite-java/src/main/java/org/openrewrite/java/PackageMatcher.java
--- a/rewrite-java/src/main/java/org/openrewrite/java/PackageMatcher.java	(revision d308e49f27ddf9bba8042d1737e40df97bcf8d04)
+++ b/rewrite-java/src/main/java/org/openrewrite/java/PackageMatcher.java	(date 1732543894454)
@@ -17,15 +17,10 @@
 
 import lombok.Getter;
 import org.jspecify.annotations.Nullable;
-import org.openrewrite.ExecutionContext;
-import org.openrewrite.Tree;
-import org.openrewrite.TreeVisitor;
-import org.openrewrite.internal.StringUtils;
 import org.openrewrite.trait.Reference;
-import org.openrewrite.xml.tree.Xml;
 
 @Getter
-public class PackageMatcher implements Reference.Renamer, Reference.Matcher {
+public class PackageMatcher implements Reference.Matcher {
 
     private final @Nullable String targetPackage;
 
@@ -53,23 +48,8 @@
     }
 
     @Override
-    public TreeVisitor<Tree, ExecutionContext> rename(String newValue) {
-        return new TreeVisitor<Tree, ExecutionContext>() {
-            @Override
-            public @Nullable Tree visit(@Nullable Tree tree, ExecutionContext ctx) {
-                if (StringUtils.isNotEmpty(newValue)) {
-                    if (tree instanceof Xml.Attribute) {
-                        return ((Xml.Attribute) tree).withValue(((Xml.Attribute) tree).getValue().withValue(getReplacement(((Xml.Attribute) tree).getValueAsString(), targetPackage, newValue)));
-                    }
-                    if (tree instanceof Xml.Tag) {
-                        if (((Xml.Tag) tree).getValue().isPresent()) {
-                            return ((Xml.Tag) tree).withValue(getReplacement(((Xml.Tag) tree).getValue().get(), targetPackage, newValue));
-                        }
-                    }
-                }
-                return super.visit(tree, ctx);
-            }
-        };
+    public Reference.Renamer renameTo(String newName) {
+        return oldName -> getReplacement(oldName, targetPackage, newName);
     }
 
     String getReplacement(String value, @Nullable String oldValue, String newValue) {
@@ -82,5 +62,4 @@
         }
         return value;
     }
-
 }
Index: rewrite-java/src/main/java/org/openrewrite/java/TypeMatcher.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/rewrite-java/src/main/java/org/openrewrite/java/TypeMatcher.java b/rewrite-java/src/main/java/org/openrewrite/java/TypeMatcher.java
--- a/rewrite-java/src/main/java/org/openrewrite/java/TypeMatcher.java	(revision d308e49f27ddf9bba8042d1737e40df97bcf8d04)
+++ b/rewrite-java/src/main/java/org/openrewrite/java/TypeMatcher.java	(date 1732543857366)
@@ -19,9 +19,6 @@
 import org.antlr.v4.runtime.CharStreams;
 import org.antlr.v4.runtime.CommonTokenStream;
 import org.jspecify.annotations.Nullable;
-import org.openrewrite.ExecutionContext;
-import org.openrewrite.Tree;
-import org.openrewrite.TreeVisitor;
 import org.openrewrite.internal.StringUtils;
 import org.openrewrite.java.internal.grammar.MethodSignatureLexer;
 import org.openrewrite.java.internal.grammar.MethodSignatureParser;
@@ -30,15 +27,13 @@
 import org.openrewrite.java.tree.TypeTree;
 import org.openrewrite.java.tree.TypeUtils;
 import org.openrewrite.trait.Reference;
-import org.openrewrite.xml.tree.Xml;
 
 import java.util.regex.Pattern;
 
 import static org.openrewrite.java.tree.TypeUtils.fullyQualifiedNamesAreEqual;
 
 @Getter
-public class TypeMatcher implements Reference.Renamer, Reference.Matcher {
-    private static final String ASPECTJ_DOT_PATTERN = StringUtils.aspectjNameToPattern(".");
+public class TypeMatcher implements Reference.Matcher {
 
     @SuppressWarnings("NotNullFieldNotInitialized")
     @Getter
@@ -121,21 +116,8 @@
     }
 
     @Override
-    public TreeVisitor<Tree, ExecutionContext> rename(String newValue) {
-        return new TreeVisitor<Tree, ExecutionContext>() {
-            @Override
-            public @Nullable Tree visit(@Nullable Tree tree, ExecutionContext ctx) {
-                if (StringUtils.isNotEmpty(newValue)) {
-                    if (tree instanceof Xml.Attribute) {
-                        return ((Xml.Attribute) tree).withValue(((Xml.Attribute) tree).getValue().withValue(newValue));
-                    }
-                    if (tree instanceof Xml.Tag) {
-                        return ((Xml.Tag) tree).withValue(newValue);
-                    }
-                }
-                return super.visit(tree, ctx);
-            }
-        };
+    public Reference.Renamer renameTo(String newName) {
+        return oldName -> newName;
     }
 
 }
Index: rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java b/rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
--- a/rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java	(revision d308e49f27ddf9bba8042d1737e40df97bcf8d04)
+++ b/rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java	(date 1732543906502)
@@ -148,7 +148,7 @@
                     for (Reference ref : references.findMatches(matcher)) {
                         matches.put(ref.getTree(), ref);
                     }
-                    return new ReferenceChangePackageVisitor(matches, matcher, newPackageName).visit(tree, ctx, requireNonNull(getCursor().getParent()));
+                    return new ReferenceChangePackageVisitor(matches, matcher.renameTo(newPackageName)).visit(tree, ctx, requireNonNull(getCursor().getParent()));
                 }
                 return tree;
             }
@@ -390,13 +390,12 @@
     private static class ReferenceChangePackageVisitor extends TreeVisitor<Tree, ExecutionContext> {
         Map<Tree, Reference> matches;
         Reference.Renamer renamer;
-        String newPackageName;
 
         @Override
         public @Nullable Tree preVisit(@Nullable Tree tree, ExecutionContext ctx) {
             Reference reference = matches.get(tree);
-            if (reference != null && reference.supportsRename()) {
-                return reference.rename(renamer, newPackageName).visit(tree, ctx, getCursor().getParent());
+            if (tree != null && reference != null && reference.supportsRename()) {
+                return reference.rename(renamer, getCursor(), ctx);
             }
             return tree;
         }
Index: rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java b/rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
--- a/rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java	(revision d308e49f27ddf9bba8042d1737e40df97bcf8d04)
+++ b/rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java	(date 1732543869973)
@@ -117,7 +117,7 @@
                     for (Reference ref : references.findMatches(matcher, Reference.Kind.TYPE)) {
                         matches.put(ref.getTree(), ref);
                     }
-                    return new ReferenceChangeTypeVisitor(matches, matcher, newFullyQualifiedTypeName).visit(tree, ctx, requireNonNull(getCursor().getParent()));
+                    return new ReferenceChangeTypeVisitor(matches, matcher.renameTo(newFullyQualifiedTypeName)).visit(tree, ctx, requireNonNull(getCursor().getParent()));
                 }
                 return tree;
             }
@@ -560,13 +560,12 @@
     private static class ReferenceChangeTypeVisitor extends TreeVisitor<Tree, ExecutionContext> {
         Map<Tree, Reference> matches;
         Reference.Renamer renamer;
-        String newFullyQualifiedName;
 
         @Override
         public @Nullable Tree preVisit(@Nullable Tree tree, ExecutionContext ctx) {
             Reference reference = matches.get(tree);
-            if (reference != null && reference.supportsRename()) {
-                return reference.rename(renamer, newFullyQualifiedName).visit(tree, ctx, getCursor().getParent());
+            if (tree != null && reference != null && reference.supportsRename()) {
+                return reference.rename(renamer, getCursor(), ctx);
             }
             return tree;
         }
Index: rewrite-core/src/main/java/org/openrewrite/trait/Reference.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/rewrite-core/src/main/java/org/openrewrite/trait/Reference.java b/rewrite-core/src/main/java/org/openrewrite/trait/Reference.java
--- a/rewrite-core/src/main/java/org/openrewrite/trait/Reference.java	(revision d308e49f27ddf9bba8042d1737e40df97bcf8d04)
+++ b/rewrite-core/src/main/java/org/openrewrite/trait/Reference.java	(date 1732543837588)
@@ -31,16 +31,16 @@
 
     String getValue();
 
-    default boolean supportsRename() {
-        return false;
-    }
-
     default boolean matches(Matcher matcher) {
         return matcher.matchesReference(this);
     }
 
-    default TreeVisitor<Tree, ExecutionContext> rename(Renamer renamer, String replacement) {
-        return renamer.rename(replacement);
+    default boolean supportsRename() {
+        return false;
+    }
+
+    default Tree rename(Renamer rename, Cursor cursor, ExecutionContext ctx) {
+        return cursor.getValue();
     }
 
     interface Provider {
@@ -52,11 +52,13 @@
 
     interface Matcher {
         boolean matchesReference(Reference value);
+        default Renamer renameTo(String newName) {
+            throw new UnsupportedOperationException();
+        }
     }
 
+    @FunctionalInterface
     interface Renamer {
-        default TreeVisitor<Tree, ExecutionContext> rename(String replacement) {
-            throw new UnsupportedOperationException();
-        }
+        String rename(String oldName);
     }
 }
Index: rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringReference.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringReference.java b/rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringReference.java
--- a/rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringReference.java	(revision d308e49f27ddf9bba8042d1737e40df97bcf8d04)
+++ b/rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringReference.java	(date 1732543857347)
@@ -17,9 +17,12 @@
 
 import lombok.Value;
 import org.jspecify.annotations.Nullable;
-import org.openrewrite.*;
-import org.openrewrite.trait.SimpleTraitMatcher;
+import org.openrewrite.Cursor;
+import org.openrewrite.ExecutionContext;
+import org.openrewrite.SourceFile;
+import org.openrewrite.Tree;
 import org.openrewrite.trait.Reference;
+import org.openrewrite.trait.SimpleTraitMatcher;
 import org.openrewrite.xml.XPathMatcher;
 import org.openrewrite.xml.tree.Xml;
 
@@ -62,6 +65,21 @@
         return true;
     }
 
+    @Override
+    public Tree rename(Renamer rename, Cursor cursor, ExecutionContext ctx) {
+        Tree tree = cursor.getValue();
+        if (tree instanceof Xml.Attribute) {
+            Xml.Attribute attribute = (Xml.Attribute) tree;
+            String renamed = rename.rename(attribute.getValue().getValue());
+            return attribute.withValue(attribute.getValue().withValue(renamed));
+        } else if (tree instanceof Xml.Tag && ((Xml.Tag) tree).getValue().isPresent()) {
+            Xml.Tag tag = (Xml.Tag) tree;
+            String renamed = rename.rename(tag.getValue().get());
+            return tag.withValue(renamed);
+        }
+        return tree;
+    }
+
     static class Matcher extends SimpleTraitMatcher<SpringReference> {
         private final Pattern referencePattern = Pattern.compile("\\p{javaJavaIdentifierStart}\\p{javaJavaIdentifierPart}*(?:\\.\\p{javaJavaIdentifierStart}\\p{javaJavaIdentifierPart}*)*");
         private final XPathMatcher classXPath = new XPathMatcher("//@class");
```

**Comment by knutwannheden** [comment]
The API proposed in this PR is in many ways also similar to what I propose in the patch. In my patch I think the API is simpler, as we don't introduce a new `ReferenceUpdateProvider` and instead just extend the already existing `Matcher`. Otherwise a lot is quite similar.

**Comment by knutwannheden** [comment]
To make my alternative easier to review and discuss, I created it as a PR here: #4714.

**Comment by timtebeek** [comment]
- Continued in https://github.com/openrewrite/rewrite/pull/4714

**Pull request closed without merging**
