### PR TITLE
Allowing for trailing dollars and percent signs in String literals

### LINKED ISSUE #4601: HCL Parser does not accept percent sign (%) in String literals
## What is the smallest, simplest way to reproduce the problem?
```
    @Test
    void percentSignInStringLiteral() {
        rewriteRun(
          hcl(
            """
              locals {
                hello = "no alcohol %"
              }
              """
          )
        );
    }
```

## What is the full stack trace of any errors you encountered?
```
[...]
Caused by: org.openrewrite.hcl.HclParsingException: Syntax error in file.tf at line 2:24 token recognition error at: '\n'.
	at org.openrewrite.hcl.HclParser$ForwardingErrorListener.syntaxError(HclParser.java:105)
	... 132 more
Caused by: LexerNoViableAltException('\n')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	... 129 more
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

No opinion yet. I haven't looked at the possible fix yet.

### LINKED ISSUE #4613: HCL Parser fails with a trailing dollar sign in String literal
## What is the smallest, simplest way to reproduce the problem?
```
    void trailingDollarSign() {
        rewriteRun(
          hcl(
            """
              locals {
                regexp = "^(.*?)-monitoring$"
              }
              """
          )
        );
    }
```

## What is the full stack trace of any errors you encountered?
```
[...]
Caused by: org.openrewrite.hcl.HclParsingException: Syntax error in file.tf at line 2:31 token recognition error at: '\n'.
	at org.openrewrite.hcl.HclParser$ForwardingErrorListener.syntaxError(HclParser.java:105)
	... 132 more
Caused by: LexerNoViableAltException('\n')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	... 129 more
```

### PR DESCRIPTION
**Pull request by mccartney**
## What's changed?
Changing the HCL lexing/parsing grammar to allow for `$` and `%` signs at the end of String literals. 

## What's your motivation?

Until now it hasn't been allowed, which I think is a bug as described in:

- fixes #4601 
- fixes #4613 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases (some already exist)

### CODE REVIEW

**Comment by mccartney** [comment]
Hmm. Now I see the autogenerated Java files by ANTLR observe a removed copyright notices. Not sure how to restore them (other than manual crafting them). Looking.

**Comment by timtebeek** [comment]
```
./gradlew licenseFormat
```
ought to help; although the bot also should chime in soon.

**Comment by mccartney** [comment]
> ./gradlew licenseFormat

Thanks! Didn't know.
I ran that in fe73bc4cb and closed all the bot suggestions.

**Comment by mccartney** [comment]
I need help in deciding what to do with the next batch of bot suggestions here.
Valid or not, but I am not sure if we want to apply bot suggestions against **generated** code. This seems counterproductive to me, but maybe this is what the project wants to enforce for all code.

Which BTW, to me is a sign this code shouldn't be checked-in to VCS.

**Review by timtebeek — COMMENTED** [review]
On the subject of the code changes here; would you mind educating me a bit on what you've changed and the process behind regenerating those parsers? 😅  Would help me review & verify, as the changes look good already but I'd like the process to be repeatable for the next one.

**Comment by mccartney** [comment]
> would you mind educating me a bit on what you've changed

Sure:
- The only file I have edited in this PR myself is the `.g4` one. The input to ANTLR.
- Then I ran `./gradlew rewrite-hcl:generateAntlrSources`, so that ANTLR generates `rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/grammar`.
- Then I added a new test of `escapingTheDollarSign` to ensure the `$${something}` case is properly handled.

**Comment by mccartney** [comment]
> I'd like the process to be repeatable for the next one.

IMHO the best way for this process be repeatable and self-documented is #4626

**Review by timtebeek — APPROVED** [review]
Great to see these issues resolved so quickly after you've reported them here. Thanks for the helpful pointers as well on a part I hadn't seen much of before. 🙏🏻

**Pull request merged**
