### PR TITLE
fix: CommentOutProperty to work with single keys

### PR DESCRIPTION
**Pull request by jonesbusy**
Just demonstrate it doesn't works as expected (or I didn't understood the recipe).

Instead of commenting out the property it's removed.

issue

### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks for the runnable example here @jonesbusy ! Had a brief look, and I suspect there's an logical error in the recipe.

As a bit of background: comments are not floating elements, but attached to the next LST element. That allows them to move with the code, as opposed to having to always check of and move both with any restructuring. In this case, it seems the recipe has made the assumption that we can remove the comment, and add it to the "next" element. But in your case there is no next element, so the comment is accidentally lost.

What we should be doing here (I think) is to add any left over comment to the `eof` of the matching document / documents (TBD). That should then make sure we don't accidentally lose any commented out elements at the end of a doc. I hope that's clear!

**Comment by jonesbusy** [comment]
Thanks for the hint. Really helpful. I will try to take a look at it and perform also more test when the key is not the last element of the document

**Review by timtebeek — APPROVED** [review]
Thanks for taking this on! Exactly what I had in mind indeed; I've added & fixed another test case where there might be multiple documents, and with that I think we're good to merge once the tests pass.

**Comment by jonesbusy** [comment]
Thanks for the fixed and merge! Much appreciated

**Pull request merged**
