### PR TITLE
Fix for type cast error in Gradle AddDependency recipe.

### PR DESCRIPTION
**Pull request by jeremyg484**
## What's changed?

An instanceof check for JavaSourceFile is added to AddDependency.java.

## What's your motivation?

Without this type check, the invocation of `UsesType` in `AddDependency`'s scanning visitor fails when encountering non-Java files such as a properties file.

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've added the license header to any new files through `./gradlew licenseFormat`
- [x] I've used the IntelliJ auto-formatter on affected files
- [x] I've updated the documentation (if applicable)

### CODE REVIEW

**Comment by shanman190** [comment]
Hi @jeremyg484, I'm not sure if I missed something here, but it appears that `UsesType`'s first check is an instanceof `JavaSourceFile` in it's visit method. So unless I've totally missed something, then removing the if check in `AddDependency` should still result in a passing test case.

**Comment by jeremyg484** [comment]
> Hi @jeremyg484, I'm not sure if I missed something here, but it appears that `UsesType`'s first check is an instanceof `JavaSourceFile` in it's visit method. So unless I've totally missed something, then removing the if check in `AddDependency` should still result in a passing test case.

@shanman190 The problem comes here: https://github.com/openrewrite/rewrite/blob/011685861c1cc49a3b8e8ad77c5d45314ec60f5a/rewrite-java/src/main/java/org/openrewrite/java/search/UsesType.java#L82

The `tree` is cast to `org.openrewrite.java.tree.J`. Running the test case I included without the change to `AddDependency` will result in a `ClassCastException` at that line.

Note that the Maven version of `AddDependency` already has the type check:
https://github.com/openrewrite/rewrite/blob/011685861c1cc49a3b8e8ad77c5d45314ec60f5a/rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java#L173

**Comment by jeremyg484** [comment]
@shanman190 It looks like https://github.com/jeremyg484/rewrite/commit/011685861c1cc49a3b8e8ad77c5d45314ec60f5a has taken an alternate (better) approach to fixing this same problem. My test case now passes after pulling in this change.

That said, the above commit does not include a test case, so it might still be worth merging the added test case from this PR. I've updated the PR branch accordingly.

**Comment by shanman190** [comment]
I agree. This test case can help to ensure that specific check is made which would be good going forward.

**Pull request merged**
