### PR TITLE
Fix Control Flow Graph Generation for iterable for each

### LINKED ISSUE #2128: Issue discovered with `src/main/java/org/bytedeco/javacpp/tools/Parser.java`
### Problem
  > Describe the issue you are experiencing.
  
  ### Expected behavior
A fake conditional should have been generated for Control Flow analysis.

The problem is that it looks like replace isn't working in templates when the type is a ternary.
```java
JavaTemplate.builder(this::getCursor, "Arrays.asList(#{any()}).iterator().hasNext()")
                            .imports("java.util.Arrays")
                            .build()
```

  
  ### Example diff
  
  
  ```diff
                                   + "{ this(" + (dim > 0 ? "Math.min(firstValue.length, secondValue.length)" : "") + "); put(firstValue, secondValue); }\n";
                     }
                 } else if (resizable && firstType == null && secondType == null) {
-                    for (String javaName : valueType.javaNames != null ? valueType.javaNames : new String[]{valueType.javaName}) {
+                    
! 
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Ternary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Ternary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader 'app')
  org.openrewrite.java.controlflow.ControlFlow$ControlFlowAnalysis.createFakeConditionalMethod(ControlFlow.java:622)
  org.openrewrite.java.controlflow.ControlFlow$ControlFlowAnalysis.visitForEachLoop(ControlFlow.java:602)
  org.openrewrite.java.controlflow.ControlFlow$ControlFlowAnalysis.visitForEachLoop(ControlFlow.java:90)
  org.openrewrite.java.tree.J$ForEachLoop.acceptJava(J.java:1810)
  org.openrewrite.java.tree.J.accept(J.java:55)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:145)
  org.openrewrite.java.controlflow.ControlFlow$ControlFlowAnalysis.visitRecursive(ControlFlow.java:171)
  ...

!for (String javaName : valueType.javaNames != null ? valueType.javaNames : new String[]{valueType.javaName}) {
                         if (dim < 2 && !javaName.equals("int") && !javaName.equals("long")) {
                             decl.text += "    public " + containerType.javaName + "(" + javaName + " value) { this(1); put(0, value); }\n";
                         }
  ```
  
  
  #### Recipes in example diff:
  - org.openrewrite.java.security.PartialPathTraversalVulnerability
  
  ### References:
  - Recipe ID: `undefined`
  - Recipe Name: "Partial path traversal vulnerability"
  - Repository: wumo/gradle-javacpp-plugin/master
  - Created at Mon Aug 08 2022 14:32:28 GMT-0700 (Pacific Daylight Time)

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #2128

### CODE REVIEW

**Comment by knutwannheden** [comment]
@JLLeitschuh I take it that my recent change to allow `JavaTemplate` to replace expressions in more contexts didn't help you here?

**Comment by JLLeitschuh** [comment]
How recent? This change was originally forked mid-last week. Although I just rebased.

**Comment by knutwannheden** [comment]
I am talking about the changes made here: rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java

I just thought I should mention it, although I have not looked at your PR in detail so I don't know if that would help with any of your workarounds or not.

**Comment by knutwannheden** [comment]
Wrong link copied. Please see https://github.com/openrewrite/rewrite/pull/2815

**Review by sambsnyd — APPROVED** [review]

**Comment by sambsnyd** [comment]
Thanks @JLLeitschuh !

**Pull request merged**
