### PR TITLE
Add sporadically failing multi-module ChangeParentPom tests

### PR DESCRIPTION
**Pull request by timtebeek**
For https://github.com/openrewrite/rewrite/issues/1753

### CODE REVIEW

**Comment by sambsnyd** [comment]
Are the failures problems downloading things from external services? Or because our treatment of what we download is in some way inconsistent?

**Comment by timtebeek** [comment]
No hints yet in the current output, suspect it's caught somewhere. Hadn't yet made a plan how to tackle this one; welcome to have as look if you have the time (but guessing you don't :)).

**Comment by timtebeek** [comment]
Ok this change in `RewriteTest`(!) https://github.com/openrewrite/rewrite/pull/3155/commits/8d7eff280c016aa7c47238898062c29457f81ce4 frustratingly only fixes the unit test, after noticing that tests failed when the order of processed source files was anything but parent-first. That means the test does not use the same mechanism that might lead to the errors seen in #1753 ; I was so far unable to find a direct parallel in `src/main`.

@sambsnyd Any chance you know of, or could help find a similar pattern in `src/main` that might help resolve #1753 ? Or do you want to let this rest until after the large iterable changes have been applied?

**Comment by timtebeek** [comment]
Merged as we track the issue separately already, although some of the findings above might still apply. Best to have another look after 8.0

**Pull request merged**
