### PR TITLE
Parse troublesome Yaml with new workaround in workaround for underying parser bug

### PR DESCRIPTION
**Pull request by timtebeek**
## What's changed?
Prevent `IndexOutOfBoundsException` with new workaround for issues in the underlying `YamlParser` events.

## What's your motivation?
Received reports about failures with a particular Yaml snippet; with this exact snippet you hit the new conditional.
Even if you change strings in the Yaml snippet, you will not hit the new conditional; Fun times to be had tracing that down.

## Have you considered any alternatives or workarounds?
Ideally we report this upstream and see it resolved there.

## Any additional context
The earlier workaround was introduced in these two commits to work around bugs with the underlying Yaml parser we use.
- https://github.com/openrewrite/rewrite/pull/4178
- https://github.com/openrewrite/rewrite/pull/4187

### CODE REVIEW

**Comment by timtebeek** [comment]
@pdulich you might enjoy this one; a very specific Yaml snippet managed to trigger a bug in the workaround for the parser bug you discovered earlier. Those parser events sure seem off at times.

**Comment by pdulich** [comment]
Thanks for the report. I already know the cause. 

There are many other problems with the parser. Therefore, I'm completely rewriting it. 

In the meantime I can push a bugfix for this issue.

**Comment by timtebeek** [comment]
Thanks a lot! This PR already adds a minimal workaround that might cause the least amount of conflicts; are you ok with me merging this in the meantime or do you see another quick option?

**Comment by pdulich** [comment]
Oh haha. Sorry. I'm at work and only had a quick look on your comment. I didn't realize that this is a PR and not an issue. 

If I remember correctly, the real bugfix is to replace getIndex() by getPointer().

**Comment by timtebeek** [comment]
Ah perfect, trying that now; passed locally with just that replacement, thanks!

**Comment by timtebeek** [comment]
> There are many other problems with the parser. Therefore, I'm completely rewriting it.

Could you tell us a bit more about your plans here? It can at times be challenging to review large sweeping changes, as much as the effort you'd put in might be appreciated. Just want to be sure we don't end up with a PR that's hard to see through.

**Pull request merged**
