### PR TITLE
Add providedCompile to the DependencyHandlerSpec for ChangeDependency gradle 

### PR DESCRIPTION
**Pull request by burghduffkc**
## What's changed?

Added the providedCompile to the DependencyHandlerSpec and created a test for it
## What's your motivation?

If you run the gradle ChangeDependency recipe against a war project, it will not update the dependencies for the providedCompile configuration. 
### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks a lot for adding this for WAR projects @burghduffkc ; and for your patience while I was out traveling. Looking over this now it seems [the WAR plugin adds two configurations](https://docs.gradle.org/current/userguide/war_plugin.html#sec:war_dependency_management):

> The War plugin adds two dependency configurations:
> 
> **providedCompile**
> This configuration should be used for dependencies required at compilation but which are provided by the environment in which the WAR is deployed. Dependencies declared here are thus visible to the main and test compilation classpaths.
> 
> **providedRuntime**
> This configuration should be used for dependencies required at runtime but which are provided by the environment in which the WAR is deployed. Dependencies declared here are only visible to the main and test runtime classpaths.

This PR already adds `providedCompile`; do you see any reason to add or omit `providedRuntime` ?

**Review by timtebeek — APPROVED** [review]
Approved already; let me know if you'd want a follow up commit to include `providedRuntime` as well. :) Thanks again!

**Comment by burghduffkc** [comment]
I think that should be fine.  If you want I can add that and update the
tests.  Is there any reason why all known configurations cannot be added?

**Comment by timtebeek** [comment]
Thanks for the offer to help; I've pushed that change to https://github.com/openrewrite/rewrite/commit/addfc0c656978d5dc3c2f4c88a165be911e0284b directly, so we should be good. Thanks again and let me know if you have any other suggestions for improvement! :)

**Pull request merged**
