### PR TITLE
Hide Java AST elements containing padding

### PR DESCRIPTION
**Pull request by jkschneider**
Most recipe authors will want to modify the structure of the tree but defer any formatting of that structure to `AutoFormat`.

This begins the process of going through Java AST elements and presenting a view (by default) of fields that do not contain their spacing. The default getter and wither methods for fields that contain padding pass through to their getter and wither counterparts on the `Spacing` inner class of each Java AST element containing fields that have padding.

```java
MethodInvocation m = ...;

// default mode of access doesn't involve padding
Expression select = m.getSelect();
m = m.withSelect(select.withType(anotherType));

// access `getPadding()` to see a view of fields with their padding
JRightPadded<Expression> select = m.getPadding().getSelect();
m = m.withSelect(select.withAfter(select.getAfter().withWhitespace(" ")));
```

To limit allocation cost, the `Padding` inner class is only instantiated the first time it is accessed on any AST instance and then stored in a transient field.

Because the transient field is null by default and we don't want to expose its existence to constructor callers elsewhere, we have `@RequiredArgsConstructor` (the transient spacing isn't required) and `@AllArgsConstructor`. This had the knock-on effect of breaking Jackson's ability to select a constructor for deserialization (because we had `lombok.anyConstructor.addConstructorProperties=true` on in `lombok.config`).

It seems continued use of `@ConstructorProperties` is impossible then, and indeed it may have already been broken for JDK 9 under jigsaw environments based on Lombok's release notes.

The alternative was to add the Jackson named parameters module and enable the `-parameters` Java compiler option in our Gradle build so that the compiled bytecodes of Rewrite preserve parameter names (non-default option introduced in Java 8).

Since IntelliJ doesn't respect Gradle's configuration in this regard, we would have to turn on the `-parameters` flag manually from now on:

image

### CODE REVIEW

**Comment by jkschneider** [comment]
cc / @knutwannheden

**Comment by knutwannheden** [comment]
Reading through this, I very much like the proposal. It will also result in a "condensed" containment hierarchy as presented by the cursor, which again should make life easier for the recipe authors. Further, it should also pave the way for adding a parent reference to the AST, should you ever want to do that, as that would cause some of the same Lombok and Jackson headaches.

Regarding the manual setting of IDEA compiler flags: Many IDEA settings can actually be shared by including the corresponding files in the `.idea` folder in Git. I use this often to share the code style preferences. Possibly this also works for the compiler flags.

**Comment by jkschneider** [comment]
> Further, it should also pave the way for adding a parent reference to the AST

@knutwannheden You are absolutely right -- there is a clear path to this now!

**Comment by jkschneider** [comment]
Another note about Jackson here -- because we don't want Jackson to pick up non-padded getters, the first thought was to add `@JsonIgnore` to all non-padded getters. But then we do still need Jackson to serialize the padded underlying fields. Configuring `TreeSerializer` to use private fields instead of getters means we can remove `@JsonIgnore` everywhere in `J`. Combined with the removal of `@JsonCreator` everywhere in the AST, the AST will now no longer have any compile/runtime ties to Jackson, paving the way for alternative serialization mechanisms should we ever want this.

**Pull request merged**
